<<<<<<< HEAD

# Generated by Django 5.0.1 on 2024-02-26 13:44

=======
# Generated by Django 5.0.1 on 2024-02-23 11:57
>>>>>>> 57877b9 (added profile .css/js/img)

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(blank=True, default="pending", max_length=50),
                ),
                ("badge", models.ImageField(blank=True, upload_to="badge_images")),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("break", "BREAK"), ("task", "TASK")],
                        default="task",
                        max_length=5,
                    ),
                ),
                (
                    "startTime",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("endTime", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TimeTracker.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=30)),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to='avatar_images')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD

=======
>>>>>>> 57877b9 (added profile .css/js/img)
            ],
        ),
    ]
