# Generated by Django 5.0.1 on 2024-03-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.CharField(choices=[('default', '/Users/ruby/Documents/UofG/IT /Workspace/SecondSavings/mediaalarm/default.mp3'), ('marimba', '/Users/ruby/Documents/UofG/IT /Workspace/SecondSavings/mediaalarm/Marimba.mp3'), ('harp', '/Users/ruby/Documents/UofG/IT /Workspace/SecondSavings/mediaalarm/Harp.mp3')], default='default', max_length=10)),
                ('syncGoogleTask', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
