# Generated by Django 5.0.1 on 2024-02-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_time',
            field=models.FloatField(default=0),
        ),
    ]
