# Generated by Django 5.0.1 on 2024-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0007_task_chosendate_task_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='totalBreakTime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='task',
            name='totalTaskTime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='life_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
