# Generated by Django 5.0.1 on 2024-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0009_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.CharField(default='00000000', max_length=64),
        ),
    ]
