# Generated by Django 5.0.1 on 2024-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0010_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isCountDown',
            field=models.BooleanField(default=False),
        ),
    ]
