# Generated by Django 5.0.1 on 2024-03-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0002_usersetting'),
        ('TimeTracker', '0010_group_key'),
    ]

    operations = [
    ]
