# Generated by Django 5.0.1 on 2024-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0011_merge_0002_usersetting_0010_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
