# Generated by Django 5.0.1 on 2024-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0011_task_iscountdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
    ]
