# Generated by Django 5.0.1 on 2024-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0011_merge_0002_usersetting_0010_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='coin',
            field=models.IntegerField(default=1),
        ),
    ]
