# Generated by Django 5.0.1 on 2024-03-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0011_merge_0002_usersetting_0010_group_key'),
        ('TimeTracker', '0012_task_duration'),
    ]

    operations = [
    ]
