# Generated by Django 5.0.1 on 2024-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0012_usersetting_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='google_tasklist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
