# Generated by Django 5.0.1 on 2024-03-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0012_usersetting_coin'),
        ('TimeTracker', '0013_merge_20240312_2202'),
    ]

    operations = [
    ]
