name: CI/CD

on:
  push:
    branches:
      - main
      - DEVELOP
  pull_request:
    branches:
      - main
      - DEVELOP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django checks
        run: |
          # use Django migrations
          python manage.py makemigrations --check --dry-run
          # or python manage.py check
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
