name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django checks
        run: |
          # use Django migrations
          python manage.py makemigrations --check --dry-run
          # or python manage.py check
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
=======
>>>>>>> f94cfb3 ( add cicd.yaml to github workflows)
=======
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
>>>>>>> fe85251 (updated cicd.yaml set repo serect)
=======
>>>>>>> 2520f31 ( add cicd.yaml to github workflows)
=======
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
>>>>>>> 10eaeeb (updated cicd.yaml set repo serect)
          